version: '3.8'

# build let's docker-compose know where to find the Dockerfile for the backend service. The context is the current directory (that will be . in the Dockerfile), and the Dockerfile is the default name for the Dockerfile.

# celery command is the command to start the celery worker. The -A chat_app argument tells celery to use the chat_app module to find the tasks. The --loglevel=info argument sets the log level to info.

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    container_name: redis
    image: redis:latest

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis
      - rabbitmq
    ports:
      - 8001:8000
    volumes:
      - ./src:/app
      - ./docker:/app/docker
    environment:
      - DEBUG=1
      - SECRET_KEY=asdpmsapdmspdaskdaposdkas
      - ALLOWED_HOSTS=["*"]
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq:5672/
      - CELERY_BROKER_URL_RABBITMQ=pyamqp://guest:guest@rabbitmq:5672/ # TODO: configure two different brokers
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - backend
    command: celery -A chat_app worker --loglevel=info -Q general_worker_queue
    volumes:
      - ./src:/app
      - ./docker:/app/docker
    environment:
      - DEBUG=1
      - SECRET_KEY=asdpmsapdmspdaskdaposdkas
      - ALLOWED_HOSTS=["*"]
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq:5672/
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - EMAIL_BACKEND=
      - EMAIL_HOST=
      - EMAIL_HOST_USER=
      - EMAIL_HOST_PASSWORD=
      - EMAIL_PORT=
      - DEFAULT_FROM_EMAIL=

  worker1:
    container_name: otp_worker
    build:
      context: ./docker/workers/otp_worker
      dockerfile: Dockerfile
    depends_on:
      - redis
      - backend
      - rabbitmq
    command: celery -A celery_app worker --loglevel=info -Q otp_worker_queue
    volumes:
      - ./docker/workers/otp_worker:/app
    environment:
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq:5672/
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_ACCEPT_CONTENT=application/json
      - CELERY_TASK_SERIALIZER=json
      - CELERY_RESULT_SERIALIZER=json
      - EMAIL_BACKEND=
      - EMAIL_HOST=
      - EMAIL_HOST_USER=
      - EMAIL_HOST_PASSWORD=
      - EMAIL_PORT=
      - DEFAULT_FROM_EMAIL=
